services:
  note.api:
    image: ${DOCKER_REGISTRY-}noteapi
    build:
      context: .
      dockerfile: Note.API/Dockerfile
    ports:
      - "5433:5433"
    depends_on:
      - db
      - elasticsearch
    environment:
      - ASPNETCORE_URLS=http://+:5433
      - PostgresSettings__ConnectionString=Host=db;Port=5432;Database=chat;Username=admin;Password=admin
      - PostgresSettings__Schema=chat
      - ElkSettings__Uri=http://elasticsearch:9200
      - ApplicationName__Name=note
      - JwtSettings__Issuer=note
      - JwtSettings__Audience=note
      - JwtSettings__Authority=note
      - JwtSettings__JwtKey=KNGjkrngkjreg0sdfddyjfyjugyijuthdgxrftygukyhjnbcfxvdfbgnh1234tb
      - JwtSettings__Lifetime=15
      - JwtSettings__RefreshTokenValidityInDays=7
    networks:                
      - elk
      - sharednet 
  
  db:
    image: postgres:15-alpine
    container_name: postgre
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: chat
    ports:
      - "5432:5432"
    networks:                
      - elk

  elasticsearch:
    image: elasticsearch:9.2.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock: { soft: -1, hard: -1 }
    ports:
      - "9200:9200"
    networks: 
      - elk

  kibana:
    image: kibana:9.2.0
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks: 
      - elk

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - elk
    
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - elk

networks: 
    elk:
       driver: bridge
    sharednet:
       external: true
